// ============================================================
// BREAD DIARY DATA
// This file is the source of truth. The agent updates it each time
// you report a bake. You can also edit it by hand.
// Each bake is one object in the BAKES array.
// ============================================================

window.BAKES = [
  {
    id: "b1",
    number: 1,
    date: "2026-09-15",
    dateNote: "approx. (undated)",
    title: "Seeded Sandwich Loaf",
    leavening: "Instant yeast",
    status: "Baked",
    rating: 4,
    recipe: {
      breadFlour: 220,
      wholemealFlour: 105,
      plainFlour: 0,
      otherFlour: 0,
      otherFlourNote: "",
      water: 245,
      salt: 6,
      yeast: 2,
      levain: 0,
      oil: 10,
      honey: 10,
      chia: 8,
      flax: 0,
      pumpkinSeed: 0,
      sunflowerSeed: 0,
      otherSeeds: 22,
      otherSeedsNote: "pumpkin + flax + sunflower (mixed)"
    },
    environment: { temp: "33 °C", humidity: "—" },
    process: {
      levainBuild: "—",
      mixing: "Mixed everything at 1:00 PM, rested 30 min (autolyse).",
      folds: "Stretch & fold (×3) + 1 coil fold, 30 min apart. Rested another 30 min.",
      bulk: "Room temp until 3:00 PM.",
      retard: "Fridge 3:00 PM – 7:30 PM (4.5 hrs).",
      shaping: "Shaped and put into loaf tin at 8:00 PM.",
      proof: "Final proof 8:30–9:30 PM (~1 hr) at room temp.",
      bake: "210 °C for 15 min with steam (hot-water tray), then 190 °C for 40 min.",
      cooling: "Cooled on a rack."
    },
    notes: "Well-proofed, domed nicely, good oven bloom. Crumb open and even — great for a soft seeded sandwich loaf. Slightly uneven browning (paler on one side); the bloom split a little unevenly (unscored).",
    verdict: "Solid, reliable everyday loaf. Crumb exactly right for a sandwich style.",
    improvements: "Rotate the loaf for even browning; score deliberately for a cleaner bloom; tighter / more even shaping; longer cold retard for more flavour.",
    photos: []
  },
  {
    id: "b2",
    number: 2,
    date: "2026-09-16",
    dateNote: "",
    title: "Seeded Sourdough (first sourdough!)",
    leavening: "Sourdough",
    status: "Baked",
    rating: 4,
    score: { crumb: 4, spring: 4, crust: 4, sour: 4, flavour: 4 },
    makes: 1,
    recipe: {
      breadFlour: 180,
      wholemealFlour: 105,
      plainFlour: 0,
      otherFlour: 0,
      otherFlourNote: "",
      water: 195,
      salt: 6.5,
      yeast: 0,
      levain: 100,
      oil: 10,
      honey: 10,
      chia: 8,
      flax: 15,
      pumpkinSeed: 15,
      sunflowerSeed: 0,
      otherSeeds: 0,
      otherSeedsNote: ""
    },
    environment: { temp: "29 °C", humidity: "89 %" },
    process: {
      levainBuild: "Bakery starter, kept 2 days in fridge. Built levain 12:00 PM: 40 g starter + 40 g bread flour + 40 g water (1:1:1). Doubled & domed by ~3:00 PM.",
      mixing: "Split: 100 g levain → dough; 20 g → re-fed (20:20:20) as keeper. Mixed flours + water + levain (autolyse 30 min), then added salt, oil, honey, seeds + soaked chia.",
      folds: "3 sets of folds (stretch & coil), 30 min apart. Dough smooth, domed and glossy after fold #3.",
      bulk: "Room temp until puffy & domed (~40–50% rise) — reached by 7:00 PM.",
      retard: "Fridge from 7:00 PM (overnight retard, ~12 hrs).",
      shaping: "Shaped cold from the fridge at ~8:20 AM. Dough was soft, slack and a little sticky (acid-relaxed gluten at 73% hydration + wholemeal + chia gel). Light flour dust, taut roll into the oiled tin.",
      proof: "Final proof at room temp (29 °C / 87%). Dough went in slack and only rose ~2/3 up the tin. Poke test: spring-back slowed at ~45 min → baked. (Deliberately baked on the early side to keep it mild.)",
      bake: "210 °C / 15 min with steam (water tray), then 190 °C / 50 min — 65 min total. Good oven spring at 15 min; pulled away from tin; deep golden seed-flecked crust.",
      cooling: "Cooled fully on a rack before slicing."
    },
    notes: "First sourdough attempt. Levain from a bakery. Warm, humid conditions (29 °C / 89 %) so fermentation is fast. Went with pure sourdough (no instant yeast). Dough came together well after the first stretch & fold — pale, well-hydrated, chia gel visible. Seeds (flax + pumpkin) were too coarse and sat proud on the surface at first, but 3 sets of folds distributed them well. Keeper (20 g) fed 1:1:1 and refrigerated after ~2 hrs. Bulk dough went into the fridge at 7:00 PM — puffy, domed and glossy (~40–50% rise).",
    verdict: "First sourdough — success. Open, even, seed-studded crumb; good oven spring; deep golden crust; mild flavour (12 h retard + early bake worked). Slightly denser band near the bottom from uneven shaping.",
    improvements: "1) Dough was wet/sticky when shaping — normal for sourdough (acid-relaxed gluten); next time use WET hands + bench scraper and add little flour. 2) Shaping: couldn't flatten into an even rectangle (sticky) → uneven roll → lopsided top + dense band at the base. Flatten only ~2 cm roughly, use a scraper, pre-shape + 15 min rest. 3) Final proof went in slack and only ~2/3 up the tin — shape tighter. 4) Bake 65 min (target 55) — get a cheap instant-read thermometer and bake to 93–96 °C. 5) CRACK/CHOP + soak the seeds — worked well via folds, keep doing it. 6) Bottom looked slightly moist/dense: normal — mostly SHAPING compression (denser base band) + high hydration (wholemeal+chia) + cutting after only ~1 h. NOT a real underbake (tastes good, cuts cleanly, base feels firm). Fixes: get a thermometer & bake to 93–96 °C; shape tighter; cool 2 h+; try a baking steel/darker tin; consider dropping hydration ~3–5%. Do NOT simply add 10 more min (risks dry crust without fixing the dense band).",
    photos: ["images/bake2-bulk.jpg", "images/bake2-crumb1.jpg", "images/bake2-crumb2.jpg"]
  },
  {
    id: "b3",
    number: 3,
    date: "2026-09-19",
    dateNote: "order: pickup Sat 11 AM, pre-sliced",
    title: "Mum's Balance Loaf (white-forward, no seeds)",
    leavening: "Sourdough",
    status: "Cancelled",
    recipe: {
      breadFlour: 235,
      wholemealFlour: 90,
      plainFlour: 0,
      otherFlour: 0,
      otherFlourNote: "",
      water: 220,
      salt: 6.5,
      yeast: 0,
      levain: 70,
      oil: 12,
      honey: 12,
      chia: 0,
      flax: 0,
      pumpkinSeed: 0,
      sunflowerSeed: 0,
      otherSeeds: 0,
      otherSeedsNote: ""
    },
    environment: { temp: "29 °C", humidity: "~87 %" },
    process: {
      levainBuild: "Fri 1 PM: feed keeper (keep ~20–30 g); build levain — 20 g starter + 25 g bread flour + 25 g water (1:1:1). Ready ~4 PM.",
      mixing: "Fri ~4 PM: mix flours + water + levain (autolyse 30 min), then add salt, olive oil (12 g), honey (12 g). No seeds.",
      folds: "Fri: 3 sets of folds, 30 min apart.",
      bulk: "Fri: room temp until puffy & domed (~40–50%).",
      retard: "—",
      shaping: "Fri evening: SHAPE straight into the oiled tin (taut, even roll). Then a short room-temp proof ~20–40 min until slightly puffed (NOT to the rim), then cover and refrigerate overnight. (Cold-PROOF method — final proof happens in the fridge.)",
      proof: "Fri night → Sat: cold proof in the tin in the fridge (~10–14 hrs). Bake straight from the fridge in the morning.",
      bake: "Sat morning: preheat 210 °C + steam 20–30 min, score the cold loaf, then bake 210 °C / 15 min → 190 °C / ~45 min (a little longer than usual because it's cold). Target 93–96 °C.",
      cooling: "Cool fully on a rack (~1.5–2 h); slice ~10:45 AM for 11 AM pickup."
    },
    notes: "Order for Mum — pickup Sat 11 AM, pre-sliced. White-forward balance: wholemeal cut to 25% (from 37% in bake #2), no seeds/chia, oil + honey kept for a soft enriched crumb. Method: COLD PROOF — do all the work Friday, shape Friday night, bake straight from the fridge Saturday (bake time is flexible — no early rise needed). Less absorbent (more white flour) → may feel wetter; hold back ~10 g water if needed.",
    verdict: "Cancelled — the order was not proceeded with.",
    improvements: "PREP FRI 18 SEP (see checklist.html): feed keeper; build levain 1 PM; mix ~4 PM; folds 4:30–6; bulk; shape ~8 PM; short proof; fridge ~9 PM. SAT: preheat 210 + steam 30 min; score cold loaf; bake 210/15 → 190/~45; cool 1.5–2 h; slice ~10:45; pickup 11:00. Judge proof before chilling (slightly puffed, not to the rim). Cold dough → add a few minutes bake time. Shape with wet hands + scraper. Slice only when fully cool.",
    photos: []
  },
  {
    id: "b4",
    number: 4,
    date: "2026-09-22",
    dateNote: "started Mon 21 Sep 6 PM; bake Tue morning",
    title: "Sourdough Tin Loaf",
    leavening: "Sourdough",
    status: "Planned",
    rating: null,
    tags: "tin loaf, balance",
    makes: 1,
    sellPrice: null,
    recipe: {
      breadFlour: 235,
      wholemealFlour: 90,
      plainFlour: 0,
      otherFlour: 0,
      otherFlourNote: "",
      water: 220,
      salt: 6.5,
      yeast: 0,
      levain: 70,
      oil: 12,
      honey: 12,
      chia: 0, flax: 0, pumpkinSeed: 0, sunflowerSeed: 0, otherSeeds: 0,
      otherSeedsNote: ""
    },
    environment: { temp: "29 °C", humidity: "~87 %" },
    process: {
      levainBuild: "Mon 6:00 PM: build the SHARED levain — 30 g starter + 75 g bread flour + 75 g water (=180 g). Keep ~25–30 g of starter as the keeper (feed 1:1:1, fridge). Ready ~9 PM.",
      mixing: "Mon ~9:00 PM: dissolve the 70 g levain into 220 g WATER first, then add the flours (235 g bread + 90 g wholemeal). Autolyse 30 min. Then add salt 6.5 g + olive oil 12 g + honey 12 g.",
      folds: "Mon 9:30–11:00 PM: 3 sets of folds, 30 min apart (wet hands, gentle).",
      bulk: "Mon ~11:00 PM: bulk until puffy & domed (~40–50%).",
      retard: "—",
      shaping: "Mon ~midnight: shape taut into the oiled tin (even roll, seam down). Cover.",
      proof: "Cold proof in the fridge overnight (Mon ~midnight → Tue ~7 AM, ~7 h). The FRIDGE IS THE FINAL RISE — no separate warm proof needed. Ready when domed.",
      bake: "Tue: preheat 210 °C + steam 30 min. Take straight from the fridge, score one centre slash, bake 210 °C / 15 min → 190 °C / ~45 min (to 93–96 °C). No need to let it rise again.",
      cooling: "Cool on a rack ~1–2 h before slicing."
    },
    notes: "Shared levain with the focaccia. White-forward balance loaf (25% wholemeal), no seeds. Cold-proof method: mix + shape Monday night, bake straight from the fridge Tuesday morning.",
    verdict: "Planned — bake Tue 22 Sep morning.",
    improvements: "Mix levain into the water first. Straight-from-fridge bake (cold dough → a few extra min).",
    photos: []
  },
  {
    id: "b5",
    number: 5,
    date: "2026-09-22",
    dateNote: "started Mon 21 Sep 6 PM; bake Tue morning",
    title: "Focaccia (32×27×6 cm tray)",
    leavening: "Sourdough",
    status: "Planned",
    rating: null,
    tags: "focaccia, tray",
    makes: 1,
    sellPrice: null,
    recipe: {
      breadFlour: 385,
      wholemealFlour: 0,
      plainFlour: 0,
      otherFlour: 0,
      otherFlourNote: "",
      water: 300,
      salt: 8,
      yeast: 0,
      levain: 85,
      oil: 25,
      honey: 0,
      chia: 0, flax: 0, pumpkinSeed: 0, sunflowerSeed: 0, otherSeeds: 0,
      otherSeedsNote: ""
    },
    environment: { temp: "29 °C", humidity: "~87 %" },
    process: {
      levainBuild: "Shared levain with the loaf — 180 g built Mon 6 PM.",
      mixing: "Mon ~9:00 PM: dissolve 85 g levain in 300 g WATER, add 385 g bread flour. Autolyse 30 min. Then add salt 8 g + olive oil 25 g.",
      folds: "Mon 9:30–11:00 PM: 2–3 gentle folds (focaccia needs little structure).",
      bulk: "Mon ~11:00 PM: bulk until puffy.",
      retard: "—",
      shaping: "Mon ~midnight: generously olive-oil the 32×27×6 cm tray; spread the dough out to fill it. Cover.",
      proof: "Cold proof in the fridge overnight. Next morning it should look puffy & bubbly (~800 g dough ≈ 3 cm thick).",
      bake: "Tue: bring out ~20–30 min ahead. Dimple with oiled fingers; drizzle olive oil + toppings (rosemary, onion, tomato, olives). Bake ~230 °C / 20–25 min until golden. (Both breads fit one session — bake the loaf first.)",
      cooling: "Cool in the tray a few minutes, then on a rack."
    },
    notes: "~80% hydration, ~800 g dough for an 864 cm² tray (~3 cm thick). Cold-proofed overnight; baked straight from the fridge (bring out ~20–30 min first).",
    verdict: "Planned — bake Tue 22 Sep morning.",
    improvements: "Higher hydration than the loaf — watch it doesn't over-proof in the fridge. Toppings go on right before baking.",
    photos: []
  }
];
